apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-kuburger-fe-deployment
spec:
  selector:
    matchLabels:
      app: mini-kuburger
      type: front-end
  template:
    metadata:
      labels:
        app: mini-kuburger
        type: front-end
    spec:
      containers:
      - name: mini-kuburger-react-container
        image: ledandre/mini-kuburger:1.0.2
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: mini-kuburger-frontend
spec:
  type: NodePort
  ports:
    - 
      targetPort: 3000
      port: 3000
      nodePort: 30000
  selector:
    app: mini-kuburger
    type: front-end